apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.12.4
    helm:
      values: |
        controller:
          service:
            type: LoadBalancer
            loadBalancerIP: 172.18.0.50    # (optional) pin a static IP from pool
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy: { automated: { prune: true, selfHeal: true } }