apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/d-kholin/homelab.git
    targetRevision: main
    path: talos-dev/infra/longhorn
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy: { automated: { prune: true, selfHeal: true } }