apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  source:
    repoURL: https://github.com/you/homelab-gitops.git
    targetRevision: main
    path: talos-dev/infra/metallb
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy: { automated: { prune: true, selfHeal: true } }