apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-namespaces
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default
  source:
    repoURL: https://github.com/d-kholin/homelab.git
    targetRevision: main
    path: talos-dev/infra/namespaces
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: { prune: true, selfHeal: true }