---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: default
spec:
  encryptedData:
    api-token: AgBbeLyaSqIupa0T79OmXaB8GfwchGU/V5unMZm4HVn0X/4nA2rvpQ1iI/c6+euzlBuJ3Dul7BVfFe03Tnc4qMjNfWFGqQRJiKSvKZk80oL7BUTjxR5rKSKbGdjzI4xSCD6dwRGDv9WF43WzWeZKRaUQEpKj5smBMQVUkhwZ5X+DIaXd0/NNEQPRXpkHOcF72LAe34aNxZrPG+xMzY82cSs4vzCIZaZaGUvGnCRr983t1F5iCsFXXKb/n9e9fMdkUhTJ3Epj93YMSDB4PDmeXpldA6G87aGIGtWQJtwVDZMEfks2eDiUh7t64PgaPiZi9ApS8HytgV33o1ggv6j0hfSUtqsBZbBdx3/WRJ2Ov3i8heVIB24Vx4i64FQ//MizBgKlktj7l58KuMjoWRjyk5SBXJumjIyzFFq3anl03OU0KEBcfPG41HWVPGIN/nXK6Jp4KnzrKPcDIUBOAmKG3ZDQpbm3xLTkSjkrWp2o7bQunqZRsEls6viRvIt2YufyKmEMAVoofbdDiHvKKst28D5PuQL9ctNwv/Da4bKa4zPfwFeyMuZa9X1DbPTtiQyTXCVRDJMJH8w40ipOKdFMAS76ADpiAvrfJwEkP8/LwXF4M1u88RqjGGlXyOKXvyxDrLToSs8O4xO+ozTOVxYsFIJOinwoMfw2BPixz+fYT6B1DYnM1yeHyxxA/Ia366n4efpX3YdPyoIRHQ/gR9TyBCxxA3LCE7b33662sZStx8GAL9dDR64N53vf
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: default
    type: Opaque
